import "./globals.scss";

import type { Metadata } from "next";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <div className="h-[100vh] bg-[#FAFAFA]">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
